on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            'docker-sstc',
            'docker-notify',
            'workflows/main.yaml',
            'master',
          })
